name1 = input("Please Enter Your Name : ")
name2 = input("Please Enter her/his Name : ")
name1 = name1.lower()
digit1 = name1.count("t")
digit2 = name1.count("r")
digit3 = name1.count("u")
digit4 = name1.count("e")
digit5 = name1.count("l")
digit6 = name1.count("o")
digit7 = name1.count("v")
digit8 = name1.count("e")
sum_digit = int( digit1  +  digit2  +  digit3  +  digit4  +  digit5  +  digit6  +  digit7  +  digit8 )
# print(sum_digit)
name2 = name2.lower()
digit1 = name2.count("t")
digit2 = name2.count("r")
digit3 = name2.count("u")
digit4 = name2.count("e")
digit5 = name2.count("l")
digit6 = name2.count("o")
digit7 = name2.count("v")
digit8 = name2.count("e")
sum_digit2 = int( digit1  +  digit2  +  digit3  +  digit4  +  digit5  +  digit6  +  digit7  +  digit8 )
sum_digit_whole = sum_digit + sum_digit2
# print(sum_digit_whole)
if sum_digit_whole <= 10 or sum_digit_whole >= 90 :
    print(f"Your Love Score is {sum_digit_whole}, You go together like coke and mentos.")
elif sum_digit_whole >= 40 and sum_digit_whole <= 50 : 
    print(f"Your Love Score is {sum_digit_whole}, You are alright Together.")
else:
    print(f"Your Love Score is {sum_digit_whole}.")